site_name: Adhocracy+

nav:
  - Home: index.md
  - API:
    - django basics: django_shell_basics.md 
    - api: api.md
    - celery: celery.md 
    - ckeditor: ckeditor.md 
    - management commands: management_commands.md 
    - project insights: project_insights.md 
    - reference: reference.md 
    - translations: languages_and_translations.md 
    - architecture: software_architecture.md 
    - tests: tests.md
  - Install: installation_prod.md
  - Contribute: contributing.md


plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

